version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
    networks:
      - app-network

  app:
    depends_on:
      - mongodb
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes:
  db:

networks:
  app-network:
    driver: bridge
